# File: configs/evaluation_config.yaml
# Author: Alfrida Sabar
# Deskripsi: Konfigurasi khusus untuk evaluasi model dengan metrik komprehensif

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Override konfigurasi evaluasi dengan metrik yang lebih lengkap
evaluation:
  metrics:
    - 'precision'
    - 'recall'
    - 'mAP'
    - 'f1'
    - 'accuracy'
    - 'confusion_matrix'
  test_batch_size: 4  # Batch size lebih kecil untuk evaluasi lebih detail
  save_predictions: true
  visualize_results: true
  confidence_thresholds: [0.1, 0.25, 0.5, 0.75, 0.9]  # Evaluasi pada berbagai threshold
  per_class_metrics: true  # Hitung metrik per kelas
  per_layer_metrics: true  # Hitung metrik per layer
  
  # Konfigurasi tambahan untuk visualisasi hasil
  visualization:
    max_samples: 50  # Maksimum sample untuk visualisasi
    plot_confusion_matrix: true
    plot_precision_recall_curve: true
    plot_class_distribution: true
    save_misclassified: true  # Simpan gambar dengan klasifikasi salah
  
  # Konfigurasi untuk benchmark
  benchmark:
    device: 'cuda'
    iterations: 100
    warmup_iterations: 10
    batch_sizes: [1, 2, 4, 8, 16]  # Ukur kinerja pada berbagai batch size
    measure_memory: true
    export_metrics: true
    export_path: 'results/benchmark'

# Override konfigurasi model untuk evaluasi
model:
  confidence: 0.25  # Threshold default untuk evaluasi
  iou_threshold: 0.45
  max_detections: 300  # Lebih banyak deteksi untuk evaluasi menyeluruh
  nms_method: 'weighted'  # Gunakan Weighted-NMS untuk kinerja lebih baik

# Konfigurasi khusus untuk skenario evaluasi
scenarios:
  # Skenario 1: Evaluasi pada kondisi pencahayaan ideal
  - name: 'pencahayaan_ideal'
    subset: 'test/pencahayaan_ideal'
    description: 'Kondisi pencahayaan normal dan ideal'
    
  # Skenario 2: Evaluasi pada kondisi pencahayaan rendah
  - name: 'pencahayaan_rendah'
    subset: 'test/pencahayaan_rendah'
    description: 'Kondisi pencahayaan rendah (<100 lux)'
    
  # Skenario 3: Evaluasi pada kondisi pencahayaan berlebih
  - name: 'pencahayaan_tinggi'
    subset: 'test/pencahayaan_tinggi'
    description: 'Kondisi pencahayaan tinggi (>1000 lux)'
    
  # Skenario 4: Evaluasi pada posisi uang yang bervariasi
  - name: 'posisi_bervariasi'
    subset: 'test/posisi_bervariasi'
    description: 'Uang dengan posisi dan orientasi bervariasi'