# File: configs/augmentation_config.yaml
# Enhanced augmentation config dengan progress tracking dan dataset comparison
_base_: 'base_config.yaml'

# Augmentation specific config
augmentation:
  # Basic options (UI: basic_opts_widget)
  enabled: true
  num_variations: 3                    # IntSlider 1-10
  target_count: 500                   # IntSlider 100-2000
  output_prefix: 'aug'                # Text input
  balance_classes: true               # Checkbox
  target_split: 'train'               # Dropdown: train/valid/test
  
  # Augmentation types (UI: augtypes_opts_widget)
  types: ['combined']                 # SelectMultiple: position/lighting/combined
  
  # Position parameters (UI: advanced_opts_widget position tab)
  position:
    fliplr: 0.5                      # FloatSlider 0.0-1.0
    degrees: 10                      # IntSlider 0-30
    translate: 0.1                   # FloatSlider 0.0-0.25
    scale: 0.1                       # FloatSlider 0.0-0.25
  
  # Lighting parameters (UI: advanced_opts_widget lighting tab)
  lighting:
    hsv_h: 0.015                     # FloatSlider 0.0-0.05
    hsv_s: 0.7                       # FloatSlider 0.0-1.0
    brightness: 0.2                  # FloatSlider 0.0-0.4
    contrast: 0.2                    # FloatSlider 0.0-0.4
  
  # Processing settings
  process_bboxes: true
  validate_results: true
  move_to_preprocessed: true
  output_dir: 'data/augmented'

# Enhanced progress tracking configuration
progress:
  operations:
    augmentation:
      steps: ["validate", "balance", "augment", "normalize", "complete"]
      weights: 
        validate: 15
        balance: 10
        augment: 45
        normalize: 25
        complete: 5
      granular_tracking: true
      milestone_logging: true
    
    check_dataset:
      steps: ["locate", "analyze_raw", "analyze_preprocessed", "compare", "report"]
      weights:
        locate: 10
        analyze_raw: 30
        analyze_preprocessed: 20
        compare: 20
        report: 20
      comparison_enabled: true
    
    cleanup:
      steps: ["scan", "analyze", "confirm", "execute", "verify"]
      weights:
        scan: 15
        analyze: 10
        confirm: 5
        execute: 60
        verify: 10
      confirmation_required: true

# Dataset comparison settings
dataset_comparison:
  enabled: true
  check_preprocessing: true
  validate_consistency: true
  readiness_threshold: 0.8
  splits_to_check: ['train', 'valid', 'test']
  
  # Recommendations
  recommendations:
    missing_preprocessed: "🔄 Dataset perlu preprocessing sebelum augmentasi"
    partial_preprocessed: "⚠️ Beberapa split perlu preprocessing tambahan" 
    ready_for_augmentation: "✅ Dataset siap untuk augmentasi"
    no_raw_data: "❌ Dataset raw tidak ditemukan"

# Enhanced validation
validation:
  enabled: true
  check_raw_dataset: true
  check_preprocessed_dataset: true
  compare_datasets: true
  validate_splits: true
  
  # Validation rules
  rules:
    min_images_per_split: 10
    max_size_mb: 1000
    required_splits: ['train']
    optional_splits: ['valid', 'test']
    
# UI Integration settings
ui_integration:
  shared_progress_tracker: true
  shared_dialog_components: true
  granular_feedback: true
  real_time_updates: true
  
  # Button behavior
  buttons:
    disable_during_operation: true
    restore_after_completion: true
    show_processing_indicator: true
  
  # Confirmation dialogs
  confirmations:
    cleanup_required: true
    reset_required: true
    destructive_operations: true

# Backend service configuration
service:
  communicator_enabled: true
  progress_callback_enabled: true
  error_handling: 'comprehensive'
  logging_level: 'info'
  
  # Service methods
  methods:
    check_dataset_readiness: true
    run_full_pipeline: true
    cleanup_augmented_data: true
    get_status: true