# File: configs/augmentation_config.yaml
# Author: Alfrida Sabar (direvisi)
# Deskripsi: Konfigurasi augmentasi yang dioptimalkan untuk deteksi mata uang Rupiah

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Override konfigurasi augmentasi dari base_config
augmentation:
  # Parameter yang di-override dari base_config
  num_variations: 3               # Override dari base_config (2)
  validate_results: true          # Override dari base_config (false)
  
  # Parameter tambahan yang tidak ada di base_config
  balance_classes: true           # Seimbangkan jumlah gambar per kelas
  target_count: 500               # Target jumlah gambar per kelas
  move_to_preprocessed: true      # Pindahkan hasil ke direktori preprocessed
  
  # Jenis augmentasi yang didukung
  types:
    - 'flip'                      # Flip horizontal
    - 'rotate'                    # Rotasi gambar
    - 'brightness'                # Ubah kecerahan
    - 'contrast'                  # Ubah kontras
    - 'hsv'                       # Ubah HSV
    - 'noise'                     # Tambahkan noise
    - 'blur'                      # Tambahkan blur
  
  # Parameter augmentasi posisi yang di-override
  fliplr: 0.5                     # Probabilitas flip horizontal
  degrees: 15                     # Derajat maksimum rotasi (override dari base_config 10)
  translate: 0.15                 # Translasi maksimum (override dari base_config 0.1)
  scale: 0.15                     # Skala maksimum (override dari base_config 0.1)
  
  # Parameter augmentasi pencahayaan yang di-override
  hsv_h: 0.025                    # Perubahan hue maksimum (override dari base_config 0.015)
  hsv_s: 0.7                      # Perubahan saturation maksimum
  brightness: 0.2                 # Perubahan brightness maksimum
  contrast: 0.2                   # Perubahan contrast maksimum
  blur: 0.2                       # Parameter blur (baru)
  noise: 0.1                      # Parameter noise (baru)

# Override konfigurasi cleanup dari base_config
cleanup:
  backup_dir: 'data/backup/augmentation'  # Override dari base_config (data/backup)
  backup_count: 5  # Override dari base_config (3)
  patterns:  # Parameter baru yang menggantikan augmentation_patterns
    - 'aug_*'
    - '*_augmented*'

# Pengaturan visualisasi (parameter baru)
visualization:
  enabled: true
  sample_count: 5
  save_visualizations: true
  vis_dir: 'visualizations/augmentation'
  show_original: true
  show_bboxes: true