# File: configs/augmentation_config.yaml
# Author: Refactored (direvisi)
# Deskripsi: Konfigurasi khusus untuk augmentasi dataset dengan opsi transformasi yang valid

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Konfigurasi augmentasi yang lebih lengkap
augmentation:
  enabled: true
  num_variations: 2
  output_prefix: 'aug'
  # Tidak perlu memproses bbox jika tidak ada
  process_bboxes: true
  types: ['combined', 'position', 'lighting']
  output_dir: '/content/data/augmented'
  validate_results: true
  resume: true
  
  # Opsi augmentasi posisi dengan dokumentasi untuk properti tambahan
  position:
    fliplr: 0.5          # Probabilitas flip horizontal
    flipud: 0.0          # Probabilitas flip vertical
    degrees: 15          # Derajat maksimum rotasi (sama dengan max_angle untuk kompatibilitas)
    translate: 0.1       # Nilai maksimum translasi (sebagai fraksi dari ukuran)
    scale: 0.1           # Nilai maksimum scaling (sebagai fraksi dari ukuran)
    shear: 0.0           # Nilai maksimum shearing (0.0 = disabled)
    rotation_prob: 0.5   # Probabilitas rotasi (tambahan)
    max_angle: 30        # Sudut maksimum (tambahan, akan digunakan jika > degrees)
    flip_prob: 0.5       # Probabilitas flip (tambahan, prioritas lebih tinggi dari fliplr)
    scale_ratio: 0.3     # Rasio scaling (tambahan, sama dengan scale)
  
  # Opsi augmentasi pencahayaan (menggunakan Blur sebagai alternatif kompresi)
  lighting:
    hsv_h: 0.015         # Hue shift (0-1)
    hsv_s: 0.7           # Saturation multiplication (0-1)
    hsv_v: 0.4           # Value (brightness) multiplication (0-1)
    contrast: 0.3        # Contrast adjustment (0-1)
    brightness: 0.3      # Brightness adjustment (0-1)
    compress: 0.2        # Probabilitas efek blur
    brightness_prob: 0.5 # Probabilitas perubahan brightness (tambahan)
    brightness_limit: 0.3 # Batasan perubahan brightness (tambahan, sama dengan brightness)
    contrast_prob: 0.5   # Probabilitas perubahan contrast (tambahan)
    contrast_limit: 0.3  # Batasan perubahan contrast (tambahan, sama dengan contrast)
  
  # Augmentasi ekstrim (untuk data lebih robust) - tambahan dari base config
  extreme:
    rotation_min: 30     # Rotasi minimum (derajat)
    rotation_max: 90     # Rotasi maksimum (derajat)
    probability: 0.3     # Probabilitas

# Pengaturan pengelolaan data augmentasi
# Dokumentasi: Pengaturan untuk cleanup dan backup hasil augmentasi
cleanup:
  backup_enabled: true
  backup_dir: 'data/backup/augmentation'
  backup_count: 5        # Simpan 5 backup terakhir
  patterns:
    - 'aug_*'            # Pola file hasil augmentasi
    - '*_augmented*'     # Pola alternatif hasil augmentasi

# Pengaturan visualisasi
# Dokumentasi: Pengaturan khusus untuk visualisasi hasil augmentasi
visualization:
  enabled: true
  sample_count: 5        # Jumlah sampel untuk visualisasi
  save_visualizations: true
  vis_dir: 'visualizations/augmentation'