# File: configs/augmentation_config.yaml
# Deskripsi: Config sesuai struktur defaults.py dengan backend structure lengkap

# Data paths - backend essentials
data:
  dir: 'data'

# Form fields mapping
augmentation:
  # Basic form fields
  num_variations: 2          # IntSlider
  target_count: 200          # IntSlider  
  intensity: 0.7             # FloatSlider
  balance_classes: true      # Checkbox
  target_split: 'train'      # Dropdown
  types: ['combined']        # SelectMultiple
  
  # Advanced form fields (position)
  position:
    horizontal_flip: 0.5     # fliplr slider
    rotation_limit: 12       # degrees slider
    translate_limit: 0.08    # translate slider
    scale_limit: 0.04        # scale slider
  
  # Advanced form fields (lighting) - Updated to match augment_lighting.py extreme variations
  lighting:
    brightness_limit: 0.6    # brightness slider - Increased for extreme variations (0.2->0.5 dark, 1.5->2.5 bright)
    contrast_limit: 0.3      # contrast slider - Increased to match (0.7->1.3 range)
    hsv_hue: 15              # Increased to match (-15, 15) range  
    hsv_saturation: 20       # Increased to match (0.8, 1.2) saturation scale
  
  # Combined params (sync dengan position + lighting) - Updated to match augment_lighting.py
  combined:
    horizontal_flip: 0.5
    rotation_limit: 12
    translate_limit: 0.08
    scale_limit: 0.04
    brightness_limit: 0.6    # Updated to match lighting extreme variations
    contrast_limit: 0.3      # Updated to match lighting extreme variations
    hsv_hue: 15              # Updated to match lighting extreme variations
    hsv_saturation: 20       # Updated to match lighting extreme variations

# Normalization form fields
preprocessing:
  normalization:
    method: 'minmax'         # norm_method dropdown
    denormalize: false       # denormalize checkbox
    target_size: [640, 640]

# Validation settings for filtering invalid augmented samples
validation:
  enabled: true              # Enable sample validation
  min_bbox_size: 0.001      # Minimum bbox width/height (0.001 = 0.1% of image)
  min_valid_boxes: 1        # Minimum number of valid boxes required per sample

# Backend structure yang diharapkan service
backend:
  service_enabled: true
  progress_tracking: true
  async_processing: false
  max_workers: 4
  timeout_seconds: 300
  retry_count: 3
  validation_enabled: true

cleanup:
  default_target: 'both'     # Dropdown: 'augmented', 'samples', 'both'

# Backend essentials only
balancing:
  enabled: true
  layer_weights:
    layer1: 1.0
    layer2: 0.8
    layer3: 0.5

file_processing:
  max_workers: 4
  batch_size: 100

performance:
  num_workers: 4