# File: configs/backbone_config.yaml
# Author: Alfrida Sabar
# Deskripsi: Konfigurasi backbone dan model_type untuk SmartCash

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Konfigurasi backbone yang tersedia
backbones:
  efficientnet_b4:
    description: 'EfficientNet-B4 backbone dengan guaranteed 3 feature maps output untuk FPN-PAN'
    stride: 32
    width_coefficient: 1.4
    depth_coefficient: 1.8
    features: 1792
    stages: [32, 56, 160, 1792]
    feature_indices: [2, 3, 4]  # Indeks untuk P3, P4, P5 stages
    out_channels: [128, 256, 512]  # Channels untuk P3, P4, P5 stages
    pretrained: true
    
  cspdarknet_s:
    description: 'CSPDarknet-Small backbone yang digunakan oleh YOLOv5s'
    stride: 32
    width_coefficient: 1.0
    depth_coefficient: 1.0
    features: 1024
    stages: [64, 128, 256, 1024]
    pretrained: true

# Konfigurasi model_type yang tersedia
model_types:
  yolov5s:
    description: 'YOLOv5s dengan CSPDarknet sebagai backbone (model pembanding)'
    backbone: 'cspdarknet_s'
    use_attention: false
    use_residual: false
    use_ciou: false
    detection_layers: ['banknote']
    num_classes: 7
    img_size: 640
    pretrained: true
    
  efficient_basic:
    description: 'Model dasar tanpa optimasi khusus'
    backbone: 'efficientnet_b4'
    use_attention: false
    use_residual: false
    use_ciou: false
    detection_layers: ['banknote']
    num_classes: 7
    img_size: 640
    pretrained: true
    
  efficient_optimized:
    description: 'Model dengan EfficientNet-B4 dan FeatureAdapter'
    backbone: 'efficientnet_b4'
    use_attention: true
    use_residual: false
    use_ciou: false
    detection_layers: ['banknote']
    num_classes: 7
    img_size: 640
    pretrained: true
    
  efficient_advanced:
    description: 'Model dengan semua optimasi: FeatureAdapter, ResidualAdapter, dan CIoU'
    backbone: 'efficientnet_b4'
    use_attention: true
    use_residual: true
    use_ciou: true
    detection_layers: ['banknote']
    num_classes: 7
    img_size: 640
    pretrained: true

# Konfigurasi feature adapter
feature_adapter:
  channel_attention: true
  reduction_ratio: 16
  use_residual: false
  
# Konfigurasi eksperimen backbone
experiments:
  backbone_comparison:
    description: 'Perbandingan performa antara backbone EfficientNet-B4 dan CSPDarknet'
    backbones: ['efficientnet_b4', 'cspdarknet_s']
    metrics: ['mAP', 'inference_time', 'precision', 'recall', 'F1']
    
  feature_adapter_ablation:
    description: 'Studi ablasi untuk komponen FeatureAdapter'
    model_types: ['efficient_basic', 'efficient_optimized', 'efficient_advanced']
    metrics: ['mAP', 'inference_time']
    
  multilayer_detection:
    description: 'Eksperimen deteksi multilayer (banknote, nominal, security)'
    model_type: 'efficient_optimized'
    detection_layers: ['banknote', 'nominal', 'security']
    layer_mode: 'multilayer'
    metrics: ['mAP_per_layer', 'inference_time']
