# File: configs/dataset_config.yaml
# Author: Alfrida Sabar (direvisi)
# Deskripsi: Konfigurasi dataset dengan struktur yang kompatibel dengan base_config.yaml yang direvisi

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Override konfigurasi data dari base_config
data:
  dir: 'data'                    # Direktori utama data (path relatif)
  preprocessed_dir: 'data/preprocessed'  # Direktori untuk hasil preprocessed (path relatif)
  split_ratios:                  # Rasio split dataset
    train: 0.7
    valid: 0.15
    test: 0.15
  stratified_split: true         # Gunakan stratified split
  random_seed: 42                # Random seed untuk reproduksibilitas
  source: 'roboflow'             # Sumber dataset ('roboflow', 'local')
  roboflow:                      # Konfigurasi Roboflow
    api_key: ''                  # Diisi oleh user atau dari Google Secret
    workspace: 'smartcash-wo2us'
    project: 'rupiah-emisi-2022'
    version: '3'
    output_format: 'yolov5pytorch'
  # Parameter validasi dataset (parameter baru)
  validation:
    enabled: true
    fix_issues: true
    move_invalid: true
    invalid_dir: 'data/invalid'
    visualize_issues: false

# Konfigurasi untuk akses dan backup dataset (parameter baru)
dataset:
  backup:
    enabled: false
    dir: 'data/backup/dataset'
    count: 2
    auto: false
  
  export:
    enabled: true
    formats:
      - 'yolo'
      - 'coco'
    dir: 'data/exported'
  
  import:
    allowed_formats:
      - 'yolo'
      - 'coco'
    temp_dir: 'data/temp'

# Override konfigurasi cache dari base_config
cache:
  dir: '.cache/smartcash/dataset'  # Override dari base_config (.cache/smartcash)