# File: configs/dataset_config.yaml
# Author: Alfrida Sabar (direvisi)
# Deskripsi: Konfigurasi dataset dengan struktur yang diselaraskan dengan base_config.yaml

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Struktur direktori data yang diselaraskan
data:
  dir: "/content/data"  # Direktori utama data
  # Directory paths
  local:
    train: "/content/data/train"
    valid: "/content/data/valid"
    test: "/content/data/test"
  
  # Roboflow config
  source: "roboflow"  # 'local' atau 'roboflow'
  roboflow:
    api_key: ""  # API key diisi oleh pengguna
    workspace: "smartcash-wo2us"
    project: "rupiah-emisi-2022"
    version: "3"
  
  # Pengaturan preprocessing diselaraskan dengan base_config
  preprocessing:
    img_size: [640, 640]
    cache_dir: ".cache/smartcash"
    num_workers: 4
    
  # Split ratios (tambahan)
  split_ratios:
    train: 0.7
    valid: 0.15
    test: 0.15
  
  # Split settings (tambahan)
  stratified_split: true
  random_seed: 42

# Override konfigurasi cache untuk dataset
cache:
  enabled: true
  dir: "/content/data/.cache/smartcash"
  max_size_gb: 1.0
  ttl_hours: 24
  auto_cleanup: true
  cleanup_interval_mins: 30