# File: configs/hyperparameters_config.yaml
# Author: Alfrida Sabar (Direvisi)
# Deskripsi: Konfigurasi hyperparameter untuk optimasi dan training model

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Override parameter training dari base_config
training:
  epochs: 100  # Override dari base_config (30)
  lr: 0.01  # Override dari base_config (0.001)

# Parameter penjadwalan (parameter baru)
scheduler:
  type: 'cosine'
  warmup_epochs: 3
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1

# Parameter regularisasi (parameter baru)
regularization:
  augment: true
  dropout: 0.0

# Parameter loss (parameter baru)
loss:
  box_loss_gain: 0.05
  cls_loss_gain: 0.5
  obj_loss_gain: 1.0

# Parameter anchor (parameter baru)
anchor:
  anchor_t: 4.0
  fl_gamma: 0.0

# Override parameter early stopping
early_stopping:
  enabled: true  # Parameter baru
  patience: 15  # Override dari base_config (10)
  min_delta: 0.001  # Parameter baru

# Parameter save best model (parameter baru)
save_best:
  enabled: true
  metric: 'mAP_0.5'
