# ========================================
# SMART CASH - MODEL CONFIGURATION
# ========================================

# Model Architecture Configuration
model:
  # Backbone network architecture
  backbone: 'efficientnet_b4'  # Options: 'cspdarknet' | 'efficientnet_b4'
  model_name: 'smartcash_yolov5'
  
  # Feature optimization - enables channel attention and feature adapters
  feature_optimization:
    enabled: false  # When true, adds feature adapters with channel attention
  
  # Detection configuration
  detection_layers: ['banknote']  # Can include: 'banknote', 'nominal', 'security'
  layer_mode: 'single'  # Options: 'single' | 'multilayer'
  
  # Model parameters
  num_classes: 7  # Number of currency denominations
  img_size: 640   # Input image size (height=width)
  conf_threshold: 0.25  # Minimum confidence score for detections
  iou_threshold: 0.45   # NMS IoU threshold
  
  # Device configuration
  device: 'auto'  # Options: 'auto' (recommended), 'cuda', 'cpu', 'mps'
  
  # Mixed precision training
  mixed_precision: true  # Use mixed precision training (FP16)

# Training Configuration (Reference only - See training_config.yaml for full options)
training:
  # Core training parameters (refer to training_config.yaml for details)
  epochs: 100
  batch_size: 16
  learning_rate: 0.001
  weight_decay: 0.0005
  
  # Main configuration (refer to training_config.yaml for full options)
  optimizer: 'adam'  # Refer to training_config.yaml for supported options
  scheduler: 'cosine'  # Refer to training_config.yaml for supported options
  mixed_precision: true
  
  # Early stopping (refer to training_config.yaml for full options)
  early_stopping:
    enabled: true
    patience: 15
    metric: 'val_map50'
  
# Validation Configuration
validation:
  # Batch and inference settings
  batch_size: 32           # Batch size for validation
  conf_threshold: 0.001    # Confidence threshold for predictions
  iou_threshold: 0.65      # IoU threshold for NMS
  max_det: 300             # Maximum detections per image

  # Metrics computation
  compute_map: true        # Whether to compute mAP metrics
  iou_thresholds: [0.5]    # IoU thresholds for mAP calculation
  map_iou_range: [0.5, 0.95]  # mAP@[0.5:0.95] calculation range
  class_agnostic: false    # Whether to compute class-agnostic metrics

  # Additional metrics
  metrics:
    - 'mAP@0.5'           # Mean Average Precision at 0.5 IoU
    - 'mAP@0.5:0.95'      # Mean Average Precision across IoUs 0.5-0.95
    - 'accuracy'          # Accuracy
    - 'precision'         # Precision
    - 'recall'            # Recall
    - 'f1'                # F1 Score
    - 'inference_time'    # Average inference time per image

# Checkpoint Configuration
checkpoint:
  # Checkpoint Saving
  save_dir: 'data/checkpoints'  # Directory to save checkpoints
  format: 'best_{model_name}_{backbone}_{date:%Y%m%d}.pt'  # Checkpoint filename format
  
  # Checkpoint Management
  max_checkpoints: 5    # Maximum number of checkpoints to keep
  auto_cleanup: true    # Automatically remove old checkpoints

# Logging Configuration
logging:
  log_interval: 10  # Log every N batches
  log_artifacts: true
  log_imgs: 16  # Number of images to log
  
  # TensorBoard
  tensorboard: true
  
  # Weights & Biases
  wandb: false
  wandb_project: 'smartcash'
  
  # Comet.ml
  comet: false
  comet_project: 'smartcash'
  max_detections: 100        # Maximum number of detections per image
  
  # NMS Options
  multi_label: true     # Multiple labels per box
  agnostic_nms: false   # Class-agnostic NMS
  max_wh: 7680         # Maximum box width/height in pixels

# Data Configuration
data:
  # Directory Paths
  pretrained_dir: 'data/pretrained'  # Directory for pretrained weights
  dataset_dir: 'data/preprocessed'   # Base directory for datasets
  
  # Data Loading
  batch_size: 32
  num_workers: 4
  pin_memory: true
  
  # Dataset Splits
  splits:
    train: 'train'  # Training set directory name
    valid: 'valid'  # Validation set directory name
    test: 'test'    # Test set directory name



# Device Configuration
device:
  auto_detect: true      # Automatically select best available device
  preferred: 'cuda'      # Preferred device: 'cuda', 'cpu', 'mps'
  mixed_precision: true  # Use mixed precision training if available

# Logging Configuration
logging:
  # Logging Levels
  level: 'INFO'  # Options: 'DEBUG', 'INFO', 'WARNING', 'ERROR'
  
  # Logging Options
  progress_tracking: true  # Show progress bars
  metrics_tracking: true   # Track training metrics
  save_logs: true          # Save logs to file
  log_dir: 'logs'          # Directory to save log files
  
  # Experiment Tracking
  tensorboard: false  # Enable TensorBoard logging
  wandb: false        # Enable Weights & Biases logging
  comet: false        # Enable Comet.ml logging