# File: configs/model_config.yaml
# Author: Alfrida Sabar
# Deskripsi: Konfigurasi khusus untuk model deteksi dengan EfficientNet-B4 sebagai backbone

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Override konfigurasi model dari base_config
model:
  # Parameter baru yang tidak ada di base_config
  type: 'efficient_basic'  # Tipe model: 'efficient_basic' atau 'yolov5s'
  backbone_weights: ''  # Path ke file weights kustom
  backbone_unfreeze_epoch: 5  # Unfreeze backbone setelah epoch ini
  pretrained_weights: ''  # Path ke file weights YOLOv5
  
  # Parameter processing yang baru
  anchors: [10,13, 16,30, 33,23, 30,61, 62,45, 59,119, 116,90, 156,198, 373,326]
  strides: [8, 16, 32]
  
  # Parameter spesifikasi model yang baru
  depth_multiple: 0.67  # Faktor skala untuk kedalaman model
  width_multiple: 0.75  # Faktor skala untuk lebar model
  
  # Parameter integrasi khusus yang baru
  use_efficient_blocks: true  # Gunakan blok EfficientNet di FPN/PAN
  use_adaptive_anchors: true  # Adaptasi anchors berdasarkan dataset
  
  # Parameter optimasi model yang baru
  quantization: false
  quantization_aware_training: false
  fp16_training: true
  
  # Parameter fitur optimasi tambahan yang baru
  use_attention: false
  use_residual: false
  use_ciou: false

# Parameter khusus EfficientNet-B4 (parameter baru)
efficientnet:
  width_coefficient: 1.4
  depth_coefficient: 1.8
  resolution: 380
  dropout_rate: 0.4
  
# Parameter transfer learning (parameter baru)
transfer_learning:
  freeze_batch_norm: false
  unfreeze_after_epochs: 10

# Parameter regularisasi khusus model (parameter baru)
regularization:
  label_smoothing: 0.0

# Konfigurasi kompilasi model untuk deployment (parameter baru)
export:
  formats: ['onnx', 'torchscript']
  dynamic_batch: true
  optimize: true
  half_precision: true
  simplify: true

# Konfigurasi khusus untuk uji coba model (parameter baru)
experiments:
  # Daftar backbone yang dibandingkan
  backbones:
    - name: 'cspdarknet_s'
      description: 'YOLOv5s default backbone'
      config:
        backbone: 'cspdarknet_s'
        pretrained: true
    
    - name: 'efficientnet_b4'
      description: 'EfficientNet-B4 backbone'
      config:
        backbone: 'efficientnet_b4'
        pretrained: true
  
  # Skenario uji coba
  scenarios:
    - name: 'yolov5s'
      description: 'YOLOv5s dengan CSPDarknet sebagai backbone (model pembanding)'
      config:
        type: 'yolov5s'
        backbone: 'cspdarknet_s'
        use_attention: false
        use_residual: false
        use_ciou: false
    
    - name: 'efficient_basic'
      description: 'Model dasar dengan EfficientNet-B4 tanpa optimasi khusus'
      config:
        type: 'efficient_basic'
        backbone: 'efficientnet_b4'
        use_attention: false
        use_residual: false
        use_ciou: false
    - name: 'efficient_optimized'
      description: 'Model dasar dengan EfficientNet-B4 dengan optimasi FeatureAdapter'
      config:
        type: 'efficient_optimized'
        backbone: 'efficientnet_b4'
        use_attention: true
        use_residual: false
        use_ciou: false
    
    - name: 'efficient_advanced'
      description: 'Model dengan semua optimasi: FeatureAdapter, ResidualAdapter, dan CIoU'
      config:
        type: 'efficient_advanced'
        backbone: 'efficientnet_b4'
        use_attention: true
        use_residual: true
        use_ciou: true