# File: configs/preprocessing_config.yaml
# Deskripsi: Konfigurasi untuk preprocessing dataset SmartCash
data:
  dir: 'data'
  splits:
    train: 'data/train'
    valid: 'data/valid'
    test: 'data/test'
  output:
    preprocessed: 'data/preprocessed'

# Konfigurasi preprocessing
preprocessing:
  enabled: true  # Aktifkan preprocessing
  
  # Pengaturan validasi
  validation:
    enabled: true    # Aktifkan validasi
    move_invalid: true  # Pindahkan file yang tidak valid
    fix_issues: false   # Coba perbaiki masalah otomatis
  
  # Pengaturan normalisasi
  normalization:
    method: 'minmax'  # minmax|standard|imagenet|none
    target_size: [640, 640]  # Ukuran target untuk YOLO
    preserve_aspect_ratio: true
    denormalize: false  # Simpan dalam format ternormalisasi
  
  # Pengaturan output
  output:
    create_npy: true  # Buat file .npy
    organize_by_split: true  # Kelompokkan berdasarkan train/valid/test

# Pola penamaan file
file_naming:
  preprocessed_pattern: 'pre_{nominal}_{uuid}_{increment}'
  preserve_uuid: true  # Pertahankan UUID konsisten
  sequence_padding: 3                    # Padding untuk increment (001, 002, dst)

# File processing configuration
file_processing:
  # Threading settings
  max_workers: 4                         # Max threads for parallel processing
  batch_size: 50                         # Files per batch
  
