# File: configs/split_config.yaml
# Author: Alfrida Sabar
# Deskripsi: Konfigurasi untuk split dataset SmartCash

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Konfigurasi data untuk split dataset
data:
  # Ratio pembagian dataset
  split_ratios:
    train: 0.7
    valid: 0.15
    test: 0.15
  
  # Pengaturan stratified split untuk mempertahankan distribusi kelas
  stratified_split: true
  
  # Random seed untuk reproduksibilitas
  random_seed: 42

# Pengaturan khusus untuk proses split
split_settings:
  # Path dataset dan output
  dataset_path: 'data'
  preprocessed_path: 'data/preprocessed'
  
  # Pengaturan backup
  backup_before_split: true
  backup_dir: 'data/splits_backup'
  backup_count: 5  # Jumlah backup yang disimpan
  
  # Opsi tambahan untuk split
  preserve_dir_structure: true
  copy_instead_of_move: false
  validate_after_split: true
  
  # Pengaturan untuk file yang diproses
  include_extensions:
    - '.jpg'
    - '.jpeg'
    - '.png'
    - '.txt'  # Label files
  
  # Pengaturan untuk file yang diabaikan
  exclude_patterns:
    - '.*'      # Hidden files
    - '_*'      # Files starting with underscore
    - 'backup*' # Backup files

# Pengaturan untuk visualisasi hasil split
visualization:
  enabled: true
  show_class_distribution: true
  plot_type: 'bar'  # 'bar' atau 'pie'
  save_plots: true
  plots_dir: 'visualizations/splits'
