repos:
-   repo: local
    hooks:
    -   id: check-test-locations
        name: Check test file locations
        entry: python scripts/check_test_locations.py
        language: system
        types: [python]
        always_run: true
        verbose: true
        stages: [commit, push]
        # Run on all files, not just staged files, to catch all test files
        files: ^(tests/|smartcash/).*\.py$
        exclude: |
            (?x)^(
                smartcash/tests/.*|  # Allow tests in the tests directory
                .*/\.pytest_cache/.*|  # Ignore pytest cache
                .*/__pycache__/.*|  # Ignore Python cache
                .*/\.git/.*  # Ignore git directory
            )$

# Add other pre-commit hooks as needed
