[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --cov=smartcash --cov-report=term-missing --asyncio-mode=auto

# Asyncio configuration
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function

# Filter warnings
filterwarnings =
    ignore::DeprecationWarning:jupyter_client.connect
    ignore::DeprecationWarning:jupyter_core.paths
    ignore::pytest.PytestDeprecationWarning:asyncio
    
    # Ignore specific pytest-asyncio deprecation warnings
    ignore:There is no current event loop:DeprecationWarning
    ignore:coroutine '.*' was never awaited:RuntimeWarning

# Coverage configuration
[tool:coverage.run]
source = smartcash
omit = 
    */tests/*
    */__init__.py

[tool:coverage.report]
exclude_lines =
    pragma: no cover
    def __repr__
    raise NotImplementedError
    raise ImportError
    if __name__ == .__main__.:
    pass
    @abstractmethod
    """
    raise NotImplementedError
    raise ImportError
    if __name__ == "__main__":
    pass
    @abstractmethod
    raise ImportError
    """
