"""
File: smartcash/common/constants/paths.py
Deskripsi: Konstanta untuk path dan struktur direktori
"""

from smartcash.common.constants.core import APP_NAME, DEFAULT_DATA_DIR

# Base paths
BASE_PATH = "."
# smartcash/common/constants/paths.py
COLAB_PATH = "/content"  # Base dir di Colab
DEFAULT_CONFIG_DIR = "configs"  # Nama direktori config

# Data directories
PREPROCESSED_DIR = f"{DEFAULT_DATA_DIR}/preprocessed"
AUGMENTED_DIR = f"{DEFAULT_DATA_DIR}/augmented"
BACKUP_DIR = f"{DEFAULT_DATA_DIR}/backup"
INVALID_DIR = f"{DEFAULT_DATA_DIR}/invalid"
VISUALIZATION_DIR = f"{DEFAULT_DATA_DIR}/visualizations"
CHECKPOINT_DIR = "/runs/train/weights"
TRAIN_DIR = f"{DEFAULT_DATA_DIR}/train"
VALID_DIR = f"{DEFAULT_DATA_DIR}/valid"
TEST_DIR = f"{DEFAULT_DATA_DIR}/test"

# Colab paths
COLAB_DATASET_PATH = f"{COLAB_PATH}/{DEFAULT_DATA_DIR}"
COLAB_CONFIG_PATH = f"{COLAB_PATH}/{DEFAULT_CONFIG_DIR}"
COLAB_PREPROCESSED_PATH = f"{COLAB_PATH}/{PREPROCESSED_DIR}"
COLAB_AUGMENTED_PATH = f"{COLAB_PATH}/{AUGMENTED_DIR}"
COLAB_BACKUP_PATH = f"{COLAB_PATH}/{BACKUP_DIR}"
COLAB_INVALID_PATH = f"{COLAB_PATH}/{INVALID_DIR}"
COLAB_VISUALIZATION_PATH = f"{COLAB_PATH}/{VISUALIZATION_DIR}"

# Drive paths
DRIVE_PATH = f"{COLAB_PATH}/drive/MyDrive/{APP_NAME}"
DRIVE_DATASET_PATH = f"{DRIVE_PATH}/{DEFAULT_DATA_DIR}"
DRIVE_CONFIG_PATH = f"{DRIVE_PATH}/{DEFAULT_CONFIG_DIR}"
DRIVE_PREPROCESSED_PATH = f"{DRIVE_PATH}/{PREPROCESSED_DIR}"
DRIVE_AUGMENTED_PATH = f"{DRIVE_PATH}/{AUGMENTED_DIR}"
DRIVE_BACKUP_PATH = f"{DRIVE_PATH}/{BACKUP_DIR}"
DRIVE_INVALID_PATH = f"{DRIVE_PATH}/{INVALID_DIR}"
DRIVE_VISUALIZATION_PATH = f"{DRIVE_PATH}/{VISUALIZATION_DIR}"