_base_: base_config.yaml
cache:
  dir: .cache/smartcash/dataset
config_version: '1.0'
data:
  dir: data
  preprocessed_dir: data/preprocessed
  random_seed: 42
  roboflow:
    api_key: ''
    output_format: yolov5pytorch
    project: rupiah-emisi-2022
    version: '3'
    workspace: smartcash-wo2us
  source: roboflow
  split_ratios:
    test: 0.1
    train: 0.7
    valid: 0.2
  stratified_split: true
  validation:
    enabled: true
    fix_issues: true
    invalid_dir: data/invalid
    move_invalid: true
    visualize_issues: false
dataset:
  backup:
    auto: false
    count: 2
    dir: data/backup/dataset
    enabled: true
  export:
    dir: data/exported
    enabled: true
    formats:
    - yolo
    - coco
  import:
    allowed_formats:
    - yolo
    - coco
    temp_dir: data/temp
split_settings:
  backup_before_split: true
  backup_dir: data/splits_backup
  dataset_path: data
  preprocessed_path: data/preprocessed
updated_at: '2025-06-26 03:14:39'
