# File: configs/augmentation_config.yaml
# Author: Alfrida Sabar (Enhanced dengan CommonInitializer support)
# Deskripsi: Konfigurasi augmentasi yang kompatibel dengan UI form mapping

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Override dan enhance konfigurasi augmentasi
augmentation:
  # Parameter dasar - mapping dari basic_opts_widget
  enabled: true
  num_variations: 3               # IntSlider: 1-10
  target_count: 500              # IntSlider: 100-2000
  output_prefix: 'aug'           # Text input
  balance_classes: true          # Checkbox - Layer 1 & 2 only
  target_split: 'train'          # Dropdown: train/valid/test
  move_to_preprocessed: true     # Move hasil ke preprocessed
  
  # Jenis augmentasi - mapping dari augtypes_opts_widget
  types:
    - 'combined'                 # SelectMultiple: combined/position/lighting
    - 'position'
    - 'lighting'
  
  # Parameter posisi - mapping dari advanced_opts_widget position tab
  position:
    fliplr: 0.5                  # FloatSlider: 0.0-1.0
    degrees: 10                  # IntSlider: 0-30 (reduced dari 15)
    translate: 0.1               # FloatSlider: 0.0-0.25 (reduced dari 0.15)
    scale: 0.1                   # FloatSlider: 0.0-0.25 (reduced dari 0.15)
  
  # Parameter pencahayaan - mapping dari advanced_opts_widget lighting tab
  lighting:
    hsv_h: 0.015                 # FloatSlider: 0.0-0.05 (reduced dari 0.025)
    hsv_s: 0.7                   # FloatSlider: 0.0-1.0
    brightness: 0.2              # FloatSlider: 0.0-0.4 (reduced dari 0.3)
    contrast: 0.2                # FloatSlider: 0.0-0.4 (reduced dari 0.3)
  
  # Parameter processing
  process_bboxes: true
  validate_results: true
  resume: false
  output_dir: 'data/augmented'
  
  # Progress tracking steps - untuk progress tracker baru
  pipeline_steps:
    prepare: 10                  # Data preparation
    augment: 50                  # Main augmentation process
    normalize: 30                # Normalization step
    verify: 10                   # Verification step
  
  # Step weights untuk granular progress
  step_weights:
    prepare: 10
    augment: 50
    normalize: 30
    verify: 10

# Override konfigurasi cleanup
cleanup:
  backup_enabled: true
  backup_dir: 'data/backup/augmentation'
  backup_count: 5
  patterns:
    - 'aug_*'
    - '*_augmented*'
    - '*_processed*'
  
  # Cleanup steps untuk progress tracker
  cleanup_steps:
    locate: 10                   # Find files to cleanup
    analyze: 20                  # Analyze cleanup scope
    backup: 30                   # Backup before cleanup
    execute: 40                  # Execute cleanup

# Pengaturan visualisasi
visualization:
  enabled: true
  sample_count: 5
  save_visualizations: true
  vis_dir: 'visualizations/augmentation'
  show_original: true
  show_bboxes: true

# Enhanced progress tracking configuration
progress:
  # Operation steps mapping
  operations:
    augmentation:
      steps: ["prepare", "augment", "normalize", "verify"]
      weights: {"prepare": 10, "augment": 50, "normalize": 30, "verify": 10}
      auto_hide: true
      
    check_dataset:
      steps: ["locate", "analyze_raw", "analyze_augmented", "analyze_preprocessed"]
      weights: {"locate": 10, "analyze_raw": 30, "analyze_augmented": 30, "analyze_preprocessed": 30}
      auto_hide: false
      
    cleanup:
      steps: ["locate", "analyze", "backup", "execute"]
      weights: {"locate": 10, "analyze": 20, "backup": 30, "execute": 40}
      auto_hide: true
  
  # Progress display settings
  display:
    level: 'triple'              # single/dual/triple
    show_step_info: false        # Disable step info widget
    auto_hide_delay: 3600.0      # 1 hour auto hide
    animation_speed: 0.1

# UI form validation ranges - untuk frontend validation
validation:
  ranges:
    num_variations: [1, 10]
    target_count: [100, 2000]
    fliplr: [0.0, 1.0]
    degrees: [0, 30]
    translate: [0.0, 0.25]
    scale: [0.0, 0.25]
    hsv_h: [0.0, 0.05]
    hsv_s: [0.0, 1.0]
    brightness: [0.0, 0.4]
    contrast: [0.0, 0.4]
  
  # Required fields
  required:
    - 'num_variations'
    - 'target_count'
    - 'types'
    - 'target_split'
  
  # Default values untuk form reset
  defaults:
    num_variations: 3
    target_count: 500
    output_prefix: 'aug'
    balance_classes: true
    target_split: 'train'
    types: ['combined']