# File: configs/augmentation_config.yaml
# Deskripsi: Config sesuai struktur defaults.py dengan backend structure lengkap

# Data paths - backend essentials
data:
  dir: 'data'

# Form fields mapping
augmentation:
  # Basic form fields
  num_variations: 2          # IntSlider
  target_count: 500          # IntSlider  
  intensity: 0.7             # FloatSlider
  output_prefix: 'aug'       # Text
  balance_classes: true      # Checkbox
  target_split: 'train'      # Dropdown
  types: ['combined']        # SelectMultiple
  
  # Advanced form fields (position)
  position:
    horizontal_flip: 0.5     # fliplr slider
    rotation_limit: 12       # degrees slider
    translate_limit: 0.08    # translate slider
    scale_limit: 0.04        # scale slider
  
  # Advanced form fields (lighting)
  lighting:
    brightness_limit: 0.2    # brightness slider
    contrast_limit: 0.15     # contrast slider
  
  # Combined params (sync dengan position + lighting)
  combined:
    horizontal_flip: 0.5
    rotation_limit: 12
    translate_limit: 0.08
    scale_limit: 0.04
    brightness_limit: 0.2
    contrast_limit: 0.15

# Normalization form fields
preprocessing:
  normalization:
    method: 'minmax'         # norm_method dropdown
    denormalize: false       # denormalize checkbox
    target_size: [640, 640]

# Backend structure yang diharapkan service
backend:
  service_enabled: true
  progress_tracking: true
  async_processing: false
  max_workers: 4
  timeout_seconds: 300
  retry_count: 3
  validation_enabled: true

# Backend essentials only
balancing:
  enabled: true
  layer_weights:
    layer1: 1.0
    layer2: 0.8
    layer3: 0.5

file_processing:
  max_workers: 4
  batch_size: 100

performance:
  num_workers: 4