# File: configs/augmentation_config.yaml
# Author: Alfrida Sabar (direvisi)
# Deskripsi: Konfigurasi augmentasi yang dioptimalkan untuk deteksi mata uang Rupiah

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Override konfigurasi augmentasi dari base_config
augmentation:
  # Parameter yang di-override dari base_config
  num_variations: 3  # Override dari base_config (2)
  validate_results: true  # Override dari base_config (false)
  
  # Parameter tambahan yang tidak ada di base_config
  balance_classes: true
  target_count: 500
  move_to_preprocessed: true
  
  # Parameter posisi yang di-override
  position:
    degrees: 15  # Override dari base_config (10)
    translate: 0.15  # Override dari base_config (0.1)
    scale: 0.15  # Override dari base_config (0.1)
    shear_max: 10  # Parameter baru
  
  # Parameter pencahayaan yang di-override
  lighting:
    hsv_h: 0.025  # Override dari base_config (0.015)
    blur: 0.2  # Parameter baru
    noise: 0.1  # Parameter baru

# Override konfigurasi cleanup dari base_config
cleanup:
  backup_dir: 'data/backup/augmentation'  # Override dari base_config (data/backup)
  backup_count: 5  # Override dari base_config (3)
  patterns:  # Parameter baru yang menggantikan augmentation_patterns
    - 'aug_*'
    - '*_augmented*'

# Pengaturan visualisasi (parameter baru)
visualization:
  enabled: true
  sample_count: 5
  save_visualizations: true
  vis_dir: 'visualizations/augmentation'
  show_original: true
  show_bboxes: true