data:
  classes:
  - '001'
  - '002'
  - '005'
  - '010'
  - '020'
  - '050'
  - '100'
  - 'l2_001'
  - 'l2_002'
  - 'l2_005'
  - 'l2_010'
  - 'l2_020'
  - 'l2_050'
  - 'l2_100'
  - 'l3_sign'
  - 'l3_text'
  - 'l3_thread'
  local:
    test: data/test
    train: data/train
    val: data/val
  roboflow:
    api_key: your_roboflow_api_key
    project: rupiah_emisi-baru
    version: 3
    workspace: detection-twl6q
  source: local
dataset:
  classes:
  - '001'
  - '002'
  - '005'
  - '010'
  - '020'
  - '050'
  - '100'
  - 'l2_001'
  - 'l2_002'
  - 'l2_005'
  - 'l2_010'
  - 'l2_020'
  - 'l2_050'
  - 'l2_100'
  - 'l3_sign'
  - 'l3_text'
  - 'l3_thread'
  project: rupiah_emisi-baru
  test_path: ../test/images
  train_path: ../train/images
  valid_path: ../valid/images
  version: 3
  workspace: detection-twl6q
evaluation:
  metrics:
  - accuracy
  - precision
  - recall
  - f1
  - mAP
  - inference_time
  save_path: results/visualizations
  save_visualizations: true
experiment_scenarios:
- backbone: cspdarknet
  conditions: position
  description: YOLOv5 Default (CSPDarknet) - Variasi Posisi
  name: scenario_1
- backbone: cspdarknet
  conditions: lighting
  description: YOLOv5 Default (CSPDarknet) - Variasi Pencahayaan
  name: scenario_2
- backbone: efficientnet
  conditions: position
  description: YOLOv5 + EfficientNet-B4 - Variasi Posisi
  name: scenario_3
- backbone: efficientnet
  conditions: lighting
  description: YOLOv5 + EfficientNet-B4 - Variasi Pencahayaan
  name: scenario_4
model:
  backbone: cspdarknet
  batch_size: 16
  conf_thres: 0.25
  device: ''
  img_size:
  - 640
  - 640
  iou_thres: 0.45
  max_det: 1000
  memory_limit: 0.6
  num_classes: 17  # Total class (7 banknote + 7 nominal + 3 security)
  pretrained: true
  workers: 8
training:
  batch_size: 16
  degrees: 0.0
  epochs: 100
  fliplr: 0.5
  flipud: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  image_size: 640
  learning_rate: 0.01
  lr0: 0.01
  lrf: 0.01
  mixup: 0.0
  momentum: 0.937
  mosaic: 1.0
  perspective: 0.0
  scale: 0.5
  shear: 0.0
  translate: 0.1
  warmup_epochs: 3
  weight_decay: 0.0005