# File: configs/colab_config.yaml
# Author: Alfrida Sabar (direvisi)
# Deskripsi: Konfigurasi khusus untuk lingkungan Google Colab dengan integrasi Google Drive yang ditingkatkan

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Pengaturan integrasi dengan Google Drive - diupdate
drive:
  use_drive: true                 # Aktifkan integrasi Google Drive di Colab
  sync_on_start: true             # Sinkronisasi otomatis saat startup
  sync_strategy: 'drive_priority' # Prioritaskan config dari Drive
  symlinks: true                  # Gunakan symlinks untuk koneksi ke Drive
  paths:
    smartcash_dir: 'SmartCash'    # Direktori SmartCash di Drive
    configs_dir: 'configs'        # Direktori konfigurasi di Drive
    data_dir: 'data'              # Direktori data di Drive
    runs_dir: 'runs'              # Direktori runs di Drive
    logs_dir: 'logs'              # Direktori logs di Drive

# Pengaturan untuk environment Colab
environment:
  colab: true                     # Flag untuk lingkungan Colab
  create_dirs_on_start: true      # Buat direktori yang diperlukan saat startup
  required_packages:              # Package yang diperlukan di Colab
    - 'albumentations>=1.1.0'
    - 'roboflow>=0.2.29'
    - 'PyYAML>=6.0'
    - 'tqdm>=4.64.0'
    - 'ultralytics>=8.0.0'
    - 'pandas>=1.3.5'
    - 'seaborn>=0.11.2'

# Penyesuaian untuk Google Colab TPU/GPU
model:
  use_tpu: false                  # Set ke true untuk menggunakan TPU jika tersedia
  use_gpu: true
  precision: 'mixed_float16'      # float32, mixed_float16, atau mixed_bfloat16
  batch_size_auto: true           # Otomatis menentukan batch size berdasarkan memori
  workers: 2                      # Jumlah worker rendah untuk Colab (mencegah OOM)

# Pengaturan visualisasi untuk notebook Colab
ui:
  theme: 'default'
  plot_style: 'seaborn'
  max_displayed_items: 10
  enable_animations: false        # Nonaktifkan animasi untuk kinerja lebih baik
  update_progress_bar: true
  log_to_output: true
  display_system_info: true
  interactive_plots: true
  save_outputs: true
  save_path: '{drive_dir}/outputs'  # Menggunakan placeholder drive_dir

# Penyesuaian untuk mengelola resource Colab yang terbatas
performance:
  auto_garbage_collect: true
  checkpoint_to_drive: true       # Simpan checkpoint ke Drive
  release_memory: true            # Lepaskan memori setelah training/evaluasi
  cache:
    enabled: true
    dir: '.cache/smartcash'       # Relatif ke direktori kerja
    max_size_gb: 2.0
    ttl_hours: 12                 # Waktu hidup cache lebih pendek di Colab
    auto_cleanup: true

# Pengaturan untuk runtime lanjutan
advanced:
  debug_mode: false
  profile_execution: false
  export_metrics: true
  save_every_epoch: false
  early_stopping_monitor: 'val_loss'
  check_disk_space: true
  min_free_space_gb: 5.0
  colab_runtime_alert: true       # Peringatan jika runtime akan berakhir
  auto_backup_config: true        # Backup config ke Drive