# File: configs/colab_config.yaml
# Author: Alfrida Sabar (direvisi)
# Deskripsi: Konfigurasi khusus untuk lingkungan Google Colab dengan integrasi Google Drive yang ditingkatkan

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Override pengaturan integrasi dengan Google Drive
drive:
  use_drive: true                 # Override dari base_config (false)
  symlinks: true                  # Override dari base_config (false)

# Override pengaturan environment
environment:
  colab: true                     # Override dari base_config (false)
  required_packages:              # Parameter baru
    - 'albumentations>=1.1.0'
    - 'roboflow>=0.2.29'
    - 'PyYAML>=6.0'
    - 'tqdm>=4.64.0'
    - 'ultralytics>=8.0.0'
    - 'pandas>=1.3.5'
    - 'seaborn>=0.11.2'

# Override pengaturan model untuk Colab
model:
  use_tpu: false                  # Parameter baru
  precision: 'mixed_float16'      # Parameter baru
  batch_size_auto: true           # Parameter baru
  workers: 2                      # Override dari base_config (4)

# Override pengaturan UI untuk Colab
ui:
  max_displayed_items: 10         # Override dari base_config (20)
  enable_animations: false        # Override dari base_config (true)
  # Parameter baru
  update_progress_bar: true
  log_to_output: true
  display_system_info: true
  interactive_plots: true
  save_outputs: true
  save_path: '{drive_dir}/outputs'

# Override pengaturan performance untuk Colab
performance:
  auto_garbage_collect: true      # Override dari base_config (false)
  release_memory: true            # Override dari base_config (false)
  # Parameter baru
  checkpoint_to_drive: true
  cache:
    max_size_gb: 2.0              # Override dari base_config (1.0)
    ttl_hours: 12                 # Override dari base_config (24)

# Pengaturan untuk runtime lanjutan (parameter baru)
advanced:
  debug_mode: false
  profile_execution: false
  export_metrics: true
  save_every_epoch: false
  early_stopping_monitor: 'val_loss'
  check_disk_space: true
  min_free_space_gb: 5.0
  colab_runtime_alert: true
  auto_backup_config: true