# Configuration for SmartCash in Google Colab environment
use_drive: true
project_path: "/content/drive/MyDrive/SmartCash"

# Environment settings
is_colab: true
runtime:
  tensorflow: true
  pytorch: true
  cuda: true

# Data directories
data_dir: "${project_path}/data"
dataset_dir: "${data_dir}/datasets"
model_dir: "${project_path}/models"
checkpoints_dir: "${model_dir}/checkpoints"
export_dir: "${model_dir}/exported"
logs_dir: "${project_path}/logs"

# Dataset configuration
dataset:
  default_source: "roboflow"
  formats:
    - "yolo"
    - "coco"
  preprocessing:
    img_size: 640
    batch_size: 16
    augmentation: true

# UI configuration
ui:
  theme: "light"
  log_level: "INFO"
  show_advanced: false