# File: configs/dataset_config.yaml
# Author: Alfrida Sabar (direvisi)
# Deskripsi: Konfigurasi dataset dengan struktur yang kompatibel dengan base_config.yaml yang direvisi

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Override konfigurasi data dari base_config
data:
  # Parameter validasi dataset (parameter baru)
  validation:
    enabled: true
    fix_issues: true
    move_invalid: true
    invalid_dir: 'data/invalid'
    visualize_issues: false

# Konfigurasi untuk akses dan backup dataset (parameter baru)
dataset:
  backup:
    enabled: true
    dir: 'data/backup/dataset'
    count: 3
    auto: false
  
  export:
    enabled: true
    formats:
      - 'yolo'
      - 'coco'
    dir: 'data/exported'
  
  import:
    allowed_formats:
      - 'yolo'
      - 'coco'
      - 'voc'
    temp_dir: 'data/temp'

# Override konfigurasi cache dari base_config
cache:
  dir: '.cache/smartcash/dataset'  # Override dari base_config (.cache/smartcash)