custom_packages: ''
selected_packages:
- scikit_learn
- opencv
- notebook_deps
- python-dotenv
- pyyaml
- albumentations
- ultralytics
- torch
- pandas
- matplotlib
- torchvision
- pybboxes
- pytz
- tensorboard
- pytorch
- numpy
- yaml_parser
- scipy
- thop
- ipywidgets
- opencv-python
- timm
- sahi
- ipython
- pillow
uninstalled_defaults: []
