base_dir: /Users/masdevid/Projects/smartcash
config_path: /Users/masdevid/Projects/smartcash/configs
dataset_path: /Users/masdevid/Projects/smartcash/data
drive_mounted: false
drive_path: null
environment:
  architecture: 64bit
  cuda_available: 'False'
  cuda_version: unknown
  gpu: none
  memory: 16.00 GB
  platform: macOS-15.5-arm64-arm-64bit
  processor: arm
  python_version: 3.12.4
  system: Darwin
model_path: /Users/masdevid/Projects/smartcash/models
