# Evaluation Configuration
# ---------------------
# Configuration for model evaluation pipeline

evaluation:
  # Data paths
  data:
    test_dir: 'data/preprocessed/test'     # Source test data
    evaluation_dir: 'data/evaluation'         # Base output directory
    results_dir: 'data/evaluation/results'    # Results storage

  # Evaluation scenarios
  scenarios:
    position_variation:   # Position variation analysis
      name: 'Position Variation'
      enabled: true
      augmentation_config:
        num_variations: 5

    lighting_variation:   # Lighting condition analysis
      name: 'Lighting Variation'
      enabled: true
      augmentation_config:
        num_variations: 5

  # Metrics configuration
  metrics:
    map:  # Mean Average Precision
      enabled: true
      iou_thresholds: [0.5, 0.75]

    precision_recall:  # Precision/Recall metrics
      enabled: true
      confidence_threshold: 0.25
      iou_threshold: 0.5
      per_class: true

    f1_score:  # F1 Score calculation
      enabled: true
      beta: 1.0
      per_class: true

    inference_time:  # Timing metrics
      enabled: true

  # Checkpoint management
  checkpoints:
    auto_select_best: true
    sort_by: 'val_map'
    max_checkpoints: 10

  # Analysis modules
  analysis:
    currency_analysis:  # Currency-specific metrics
      enabled: true
      primary_layer: 'banknote'
      confidence_threshold: 0.3

    class_analysis:  # Class-wise metrics
      enabled: true
      compute_confusion_matrix: true