# File: smartcash/configs/evaluation_config.yaml
# Deskripsi: Konfigurasi evaluation pipeline untuk research scenarios

evaluation:
  # Research scenarios configuration
  scenarios:
    position_variation:
      enabled: true
      name: "Variasi Posisi Pengambilan Gambar"
      augmentation_config:
        num_variations: 5
        rotation_range: [-30, 30]
        translation_range: [-0.2, 0.2]
        scale_range: [0.8, 1.2]
        perspective_range: 0.1
        horizontal_flip: 0.5
    
    lighting_variation:
      enabled: true
      name: "Variasi Pencahayaan"
      augmentation_config:
        num_variations: 5
        brightness_range: [-0.3, 0.3]
        contrast_range: [0.7, 1.3]
        gamma_range: [0.7, 1.3]
        hsv_hue: 15
        hsv_saturation: 20
  
  # Metrics configuration
  metrics:
    map:
      enabled: true
      iou_thresholds: [0.5, 0.75]
      confidence_threshold: 0.001
      max_detections: 100
    
    accuracy:
      enabled: true
      confidence_threshold: 0.25
      iou_threshold: 0.5
    
    precision_recall:
      enabled: true
      per_class: true
      confidence_threshold: 0.25
    
    f1_score:
      enabled: true
      per_class: true
      beta: 1.0
    
    inference_time:
      enabled: true
      warmup_runs: 10
      measurement_runs: 100
      batch_sizes: [1, 4, 8, 16]
  
  # Data configuration
  data:
    test_dir: 'data/preprocessed/test'
    evaluation_dir: 'data/evaluation'
    results_dir: 'data/evaluation/results'
    reports_dir: 'data/evaluation/reports'
    
  # Checkpoint selection
  checkpoints:
    auto_select_best: true
    filter_by_backbone: false
    min_map_threshold: 0.5
    sort_by: 'val_map'  # val_map, val_loss, date
    max_checkpoints: 10

# Analysis configuration
analysis:
  currency_analysis:
    enabled: true
    primary_layer: 'banknote'        # Main detection layer
    confidence_boost_layer: 'nominal' # Confidence boost
    validation_layer: 'security'     # Validation layer
    min_security_detections: 1       # Min security features for valid money
    confidence_threshold: 0.3
  
  layer_analysis:
    enabled: true
    layers: ['banknote', 'nominal', 'security']
    compute_correlation: true
  
  class_analysis:
    enabled: true
    currency_classes: [0, 1, 2, 3, 4, 5, 6]  # Main banknote classes
    compute_confusion_matrix: true

# Performance settings
performance:
  batch_size: 16
  num_workers: 4
  device: 'auto'  # auto, cpu, cuda
  mixed_precision: true
  max_memory_gb: 8.0

# Output settings
output:
  save_predictions: true
  save_visualizations: true
  export_formats: ['json', 'csv']
  detailed_reports: true