# File: configs/model_config.yaml
# Author: Alfrida Sabar
# Deskripsi: Konfigurasi khusus untuk model deteksi dengan EfficientNet-B4 sebagai backbone

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Konfigurasi utama model sesuai dengan ModelConfig di model_config.py
model:
  # Informasi dasar model
  name: 'smartcash_model'
  img_size: [640, 640]
  batch_size: 16
  workers: 4
  
  # Konfigurasi backbone dan tipe model
  backbone: 'efficientnet_b4'  # Sesuai dengan SUPPORTED_BACKBONES di model_constants.py
  model_type: 'efficient_optimized'  # Tipe model: 'efficient_basic', 'efficient_optimized', 'efficient_advanced', 'yolov5s'
  pretrained: true
  freeze_backbone: true
  
  # Parameter optimasi model sesuai dengan OPTIMIZED_MODELS di model_constants.py
  use_attention: true  # Gunakan FeatureAdapter untuk optimasi
  use_residual: false  # Gunakan ResidualAdapter
  use_ciou: false  # Gunakan CIoU loss
  
  # Parameter tambahan model
  num_repeats: 3
  
  # Parameter processing
  anchors: [10,13, 16,30, 33,23, 30,61, 62,45, 59,119, 116,90, 156,198, 373,326]
  strides: [8, 16, 32]
  
  # Parameter feature adapter
  feature_indices: [2, 3, 4]  # Indeks untuk P3, P4, P5 stages sesuai DEFAULT_EFFICIENTNET_INDICES
  out_channels: [128, 256, 512]  # Channels untuk P3, P4, P5 stages sesuai YOLO_CHANNELS
  channel_attention: true  # Gunakan channel attention pada feature adapter
  reduction_ratio: 16  # Reduction ratio untuk channel attention

# Konfigurasi training sesuai dengan DEFAULT_MODEL_CONFIG_FULL di model_constants.py
training:
  epochs: 100
  lr: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  layer_mode: 'single'  # Mode layer: 'single' atau 'multilayer'
  
  # Augmentasi training sesuai dengan implementasi di dataset/augmentor
  fliplr: 0.5                     # Probabilitas flip horizontal
  flipud: 0.0                     # Probabilitas flip vertikal (tidak digunakan)
  scale: 0.1                      # Skala maksimum (persen)
  hsv_h: 0.015                    # Perubahan hue maksimum
  hsv_s: 0.7                      # Perubahan saturation maksimum
  hsv_v: 0.4                      # Perubahan value maksimum
  translate: 0.1                  # Translasi maksimum (persen)
  degrees: 10                     # Derajat maksimum rotasi
  brightness: 0.2                 # Perubahan brightness maksimum
  contrast: 0.2                   # Perubahan contrast maksimum

# Konfigurasi layer deteksi sesuai dengan DETECTION_LAYERS, DETECTION_THRESHOLDS, dan LAYER_CONFIG di model_constants.py
layers:
  banknote:
    enabled: true
    threshold: 0.25
    num_classes: 7
    classes:
      - {id: 0, name: '001', desc: 'Rp1000'}
      - {id: 1, name: '002', desc: 'Rp2000'}
      - {id: 2, name: '005', desc: 'Rp5000'}
      - {id: 3, name: '010', desc: 'Rp10000'}
      - {id: 4, name: '020', desc: 'Rp20000'}
      - {id: 5, name: '050', desc: 'Rp50000'}
      - {id: 6, name: '100', desc: 'Rp100000'}
  nominal:
    enabled: true
    threshold: 0.30
    num_classes: 7
    classes:
      - {id: 7, name: 'l2_001', desc: 'Rp1000'}
      - {id: 8, name: 'l2_002', desc: 'Rp2000'}
      - {id: 9, name: 'l2_005', desc: 'Rp5000'}
      - {id: 10, name: 'l2_010', desc: 'Rp10000'}
      - {id: 11, name: 'l2_020', desc: 'Rp20000'}
      - {id: 12, name: 'l2_050', desc: 'Rp50000'}
      - {id: 13, name: 'l2_100', desc: 'Rp100000'}
  security:
    enabled: true
    threshold: 0.35
    num_classes: 3
    classes:
      - {id: 14, name: 'l3_sign', desc: 'Tanda tangan'}
      - {id: 15, name: 'l3_text', desc: 'Teks mikro'}
      - {id: 16, name: 'l3_thread', desc: 'Benang pengaman'}

# Konfigurasi optimizer sesuai dengan DEFAULT_MODEL_CONFIG_FULL
optimizer:
  type: 'SGD'
  params: {}

# Konfigurasi scheduler sesuai dengan DEFAULT_MODEL_CONFIG_FULL
scheduler:
  type: 'CosineAnnealingLR'
  params: {}

# Konfigurasi data sesuai dengan ModelConfig
data:
  train: 'data/preprocesed/train'
  val: 'data/preprocesed/valid'
  test: 'data/preprocesed/test'
  preprocessing:
    cache_dir: '.cache/smartcash'

# Konfigurasi checkpoint sesuai dengan ModelConfig
checkpoint:
  save_dir: 'runs/train/exp'
  save_interval: 10
  save_last: true
  save_best: true
  metric: 'mAP'

# Parameter khusus EfficientNet-B4 sesuai dengan SUPPORTED_BACKBONES di model_constants.py
efficientnet:
  width_coefficient: 1.4
  depth_coefficient: 1.8
  resolution: 640
  dropout_rate: 0.4

# Konfigurasi kompilasi model untuk deployment
export:
  formats: ['onnx', 'torchscript']
  dynamic_batch: true
  optimize: true
  half_precision: true
  simplify: true

# Konfigurasi khusus untuk uji coba model sesuai dengan OPTIMIZED_MODELS di model_constants.py
experiments:
  # Daftar backbone yang dibandingkan
  backbones:
    - name: 'cspdarknet_s'
      description: 'YOLOv5s default backbone'
      config:
        backbone: 'cspdarknet_s'
        pretrained: true
    
    - name: 'efficientnet_b4'
      description: 'EfficientNet-B4 backbone'
      config:
        backbone: 'efficientnet_b4'
        pretrained: true
  
  # Skenario uji coba sesuai dengan OPTIMIZED_MODELS
  scenarios:
    - name: 'yolov5s'
      description: 'YOLOv5s dengan CSPDarknet sebagai backbone (model pembanding)'
      config:
        type: 'yolov5s'
        backbone: 'cspdarknet_s'
        use_attention: false
        use_residual: false
        use_ciou: false
        detection_layers: ['banknote']
        num_classes: 7
        img_size: 640
        pretrained: true
    
    - name: 'efficient_basic'
      description: 'Model dasar dengan EfficientNet-B4 tanpa optimasi khusus'
      config:
        type: 'efficient_basic'
        backbone: 'efficientnet_b4'
        use_attention: false
        use_residual: false
        use_ciou: false
        detection_layers: ['banknote']
        num_classes: 7
        img_size: 640
        pretrained: true
    
    - name: 'efficient_optimized'
      description: 'Model dasar dengan EfficientNet-B4 dengan optimasi FeatureAdapter'
      config:
        type: 'efficient_optimized'
        backbone: 'efficientnet_b4'
        use_attention: true
        use_residual: false
        use_ciou: false
        detection_layers: ['banknote']
        num_classes: 7
        img_size: 640
        pretrained: true
    
    - name: 'efficient_advanced'
      description: 'Model dengan semua optimasi: FeatureAdapter, ResidualAdapter, dan CIoU'
      config:
        type: 'efficient_advanced'
        backbone: 'efficientnet_b4'
        use_attention: true
        use_residual: true
        use_ciou: true
        detection_layers: ['banknote']
        num_classes: 7
        img_size: 640
        pretrained: true