# File: configs/preprocessing_config.yaml
# Author: Alfrida Sabar (direvisi)
# Deskripsi: Konfigurasi khusus untuk preprocessing dataset yang konsisten dengan base_config

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Konfigurasi preprocessing yang diselaraskan
preprocessing:
  output_dir: 'data/preprocessed'  # Path relatif standar
  save_visualizations: true
  vis_dir: 'visualizations/preprocessing'  # Path relatif standar
  sample_size: 500  # Jumlah sampel maksimum untuk analisis (0 = semua)
  
  # Validasi dataset selama preprocessing
  validate:
    enabled: true
    fix_issues: true
    move_invalid: true
    visualize: true
    check_image_quality: true
    check_labels: true
    check_coordinates: true

  # Opsi normalisasi
  normalization:
    enabled: true
    method: 'minmax'  # minmax, zscore, atau whitening
    target_size: [640, 640]
    preserve_aspect_ratio: true
    normalize_pixel_values: true
    pixel_range: [0, 1]  # Range normalisasi pixel

  # Opsi analisis dataset
  analysis:
    enabled: true
    class_balance: true
    image_size_distribution: true
    bbox_statistics: true
    layer_balance: true
    
  # Opsi balancing dataset
  balance:
    enabled: false
    target_distribution: 'auto'  # auto, equal, atau dict
    methods:
      undersampling: false
      oversampling: true
      augmentation: true
    min_samples_per_class: 100
    max_samples_per_class: 1000

# Konfigurasi augmentasi diselaraskan, dengan variasi spesifik untuk preprocessing
augmentation:
  enabled: true
  num_variations: 3  # Lebih banyak variasi untuk preprocessing
  output_prefix: 'aug'
  types:
    - 'position'
    - 'lighting'
    - 'combined'
  position:
    fliplr: 0.5
    degrees: 15
    translate: 0.15
    scale: 0.15
    rotate_max: 15    # Alias untuk degrees
    shear_max: 10     # Derajat maksimum untuk shear
    translate_max: 0.15  # Alias untuk translate
    scale_max: 0.15   # Alias untuk scale
  lighting:
    hsv_h: 0.025
    hsv_s: 0.7
    hsv_v: 0.4
    contrast: [0.7, 1.3]
    brightness: [0.7, 1.3]
    blur: 0.2
    noise: 0.1
    compress: 0.2

# Konfigurasi cleanup dengan path relatif standar
cleanup:
  augmentation_patterns:
    - 'aug_.*'
    - '.*_augmented.*'
    - '.*_modified.*'
    - '.*_processed.*'
    - '.*_norm.*'
  ignored_patterns:
    - '.*\.gitkeep'
    - '.*\.DS_Store'
    - '.*\.gitignore'
  backup_dir: 'data/backup/preprocessing'  # Path relatif standar
  backup_enabled: true
  auto_cleanup_preprocessed: false  # Jangan otomatis hapus hasil preprocessing

# Pengaturan performa preprocessing (tambahan)
performance:
  num_workers: 8
  batch_size: 32
  use_gpu: true
  compression_level: 90  # Kualitas JPEG untuk output (1-100)
  max_memory_usage_gb: 4.0  # Batas penggunaan memori
  use_mixed_precision: true  # Gunakan mixed precision jika GPU tersedia