# File: configs/preprocessing_config.yaml
# Author: Alfrida Sabar (direvisi)
# Deskripsi: Konfigurasi khusus untuk preprocessing dataset yang konsisten dengan base_config

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Override konfigurasi preprocessing dari base_config
preprocessing:
  vis_dir: 'visualizations/preprocessing'  # Override dari base_config (visualizations)
  sample_size: 500  # Override dari base_config (0)
  
  # Override validasi dataset
  validate:
    visualize: true  # Override dari base_config (false)

  # Override opsi analisis dataset
  analysis:
    enabled: true  # Override dari base_config (false)

# Parameter referensi ke konfigurasi augmentasi terpisah (parameter baru)
augmentation_reference:
  config_file: 'augmentation_config.yaml'
  use_for_preprocessing: true
  preprocessing_variations: 3

# Override konfigurasi cleanup dari base_config
cleanup:
  augmentation_patterns:
    - 'aug_.*'
    - '.*_augmented.*'
    - '.*_modified.*'
    - '.*_processed.*'
    - '.*_norm.*'  # Pattern tambahan
  ignored_patterns:
    - '.*\.gitkeep'
    - '.*\.DS_Store'
    - '.*\.gitignore'  # Pattern tambahan
  backup_dir: 'data/backup/preprocessing'  # Override dari base_config (data/backup)

# Override pengaturan performa dari base_config
performance:
  num_workers: 4  # Override dari base_config (4)
  batch_size: 32  # Override dari base_config (16)
  compression_level: 90  # Parameter baru
  max_memory_usage_gb: 4.0  # Override dari base_config
  use_mixed_precision: true  # Override dari base_config (false)