# File: configs/pretrained_config.yaml
# Deskripsi: Konfigurasi khusus untuk modul pretrained model

# Inherit dari base_config.yaml
_base_: 'base_config.yaml'

# Konfigurasi model pre-trained
pretrained_models:
  models_dir: '/content/models'
  drive_models_dir: '/content/drive/MyDrive/SmartCash/models'
  
  # Konfigurasi model yang tersedia
  models:
    yolov5:
      name: 'YOLOv5s'
      url: 'https://github.com/ultralytics/yolov5/releases/download/v6.2/yolov5s.pt'
      filename: 'yolov5s.pt'
      min_size_mb: 10
      description: 'Object detection backbone'
      
    efficientnet_b4:
      name: 'EfficientNet-B4'
      url: 'https://huggingface.co/timm/efficientnet_b4.ra2_in1k/resolve/main/pytorch_model.bin'
      filename: 'efficientnet_b4_huggingface.bin'
      min_size_mb: 60
      description: 'Feature extraction backbone'

# Override cache dari base_config
cache:
  dir: '.cache/smartcash/pretrained'  # Override dari base_config (.cache/smartcash)

# Progress step definitions
progress:
  steps:
    init: {value: 0, label: 'Inisialisasi'}
    check_models: {value: 20, label: 'Memeriksa model tersedia'}
    download_start: {value: 30, label: 'Memulai download'}
    download_progress: {value: 50, label: 'Mengunduh model'}
    sync_start: {value: 80, label: 'Memulai sinkronisasi'}
    sync_complete: {value: 95, label: 'Sinkronisasi selesai'}
    complete: {value: 100, label: 'Proses selesai'}