# File: smartcash/configs/training_config.yaml
# Deskripsi: Konfigurasi training pipeline dengan parameter optimal untuk currency detection

# Training hyperparameters
training:
  epochs: 100
  batch_size: 16
  learning_rate: 0.001
  weight_decay: 0.0005
  warmup_epochs: 3
  
  # Optimizer settings
  optimizer: 'adam'          # adam, sgd, adamw
  scheduler: 'cosine'        # cosine, step, plateau, none
  mixed_precision: true      # Automatic Mixed Precision
  gradient_clip: 10.0        # Gradient clipping
  
  # Early stopping
  early_stopping:
    enabled: true
    patience: 15
    min_delta: 0.001
    metric: 'val_map'        # val_map, val_loss
    mode: 'max'              # max untuk mAP, min untuk loss
  
  # Checkpoint settings
  checkpoint:
    save_best: true
    save_last: true
    save_interval: 10        # Save every N epochs
    max_checkpoints: 5       # Keep last N checkpoints
    monitor_metric: 'val_map'
  
  # Data loading
  data:
    num_workers: 4
    pin_memory: true
    persistent_workers: true
    prefetch_factor: 2
    drop_last: true          # Drop last incomplete batch
  
  # Loss configuration
  loss:
    box_weight: 0.05         # Box regression loss weight
    obj_weight: 1.0          # Objectness loss weight  
    cls_weight: 0.5          # Classification loss weight
    focal_loss: false        # Use focal loss for classification
    label_smoothing: 0.0     # Label smoothing factor
  
  # Validation
  validation:
    interval: 1              # Validate every N epochs
    compute_map: true        # Compute mAP metrics
    save_predictions: false  # Save prediction visualizations
    conf_threshold: 0.001    # Confidence threshold untuk mAP
    iou_threshold: 0.6       # IoU threshold untuk NMS
  
# Augmentation settings (minimal untuk currency)
augmentation:
  enabled: false             # Disable karena sudah di preprocessing
  
# Logging dan monitoring
logging:
  log_dir: 'data/logs/training'
  tensorboard: false         # TensorBoard logging
  wandb: false              # Weights & Biases logging
  save_metrics_csv: true    # Save metrics ke CSV
  
# Device dan performance
device:
  auto_select: true         # Auto-select best device
  cuda_benchmark: true      # Enable CUDA benchmark
  deterministic: false      # Deterministic training (slower)
  
# Model specific
model:
  freeze_backbone_epochs: 5  # Freeze backbone untuk N epochs
  unfreeze_gradually: true   # Gradually unfreeze backbone layers