# File: configs/training_config.yaml
# Author: Alfrida Sabar (Direvisi)
# Deskripsi: Konfigurasi khusus untuk proses training dan utilitas training

# Inherit dari konfigurasi lain - Menggunakan pewarisan bertingkat
# Urutan penting: base_config -> preprocessing_config -> augmentation_config -> model_config -> backbone_config -> hyperparameters_config -> training_config
_base_: ['base_config.yaml', 'preprocessing_config.yaml', 'augmentation_config.yaml', 'model_config.yaml', 'backbone_config.yaml', 'hyperparameters_config.yaml']

# Parameter validasi (parameter baru)
validation:
  frequency: 1
  iou_thres: 0.6
  conf_thres: 0.001
  
# Parameter multi-scale training (parameter baru)
multi_scale: true

# Override konfigurasi training_utils dari base_config
training_utils:
  experiment_name: 'efficientnet_b4_training'  # Override dari base_config (training)
  checkpoint_dir: '/content/runs/train/checkpoints'  # Override dari base_config (runs/train/checkpoints)
  tensorboard: true  # Override dari base_config (false)
  log_metrics_every: 10  # Override dari base_config
  visualize_batch_every: 100  # Override dari base_config (0)
  gradient_clipping: 1.0  # Override dari base_config (0.0)
  mixed_precision: true  # Override dari base_config (false)
  layer_mode: 'single'  # Parameter baru