# File: configs/training_config.yaml
# Author: Alfrida Sabar (Direvisi)
# Deskripsi: Konfigurasi khusus untuk proses training dan utilitas training

# Inherit dari konfigurasi lain
_base_: ['base_config.yaml', 'hyperparameters_config.yaml', 'model_config.yaml']

# Parameter validasi
validation:
  frequency: 1
  iou_thres: 0.6
  conf_thres: 0.001
  
# Parameter multi-scale training
multi_scale: true

# Konfigurasi tambahan untuk proses training
training_utils:
  experiment_name: 'efficientnet_b4_training'
  checkpoint_dir: '/content/runs/train/checkpoints'
  tensorboard: true
  log_metrics_every: 10  # Log metrik setiap 10 batch
  visualize_batch_every: 100  # Visualisasi batch setiap 100 batch
  gradient_clipping: 1.0  # Clipping gradien maksimum
  mixed_precision: true  # Gunakan mixed precision training
  layer_mode: 'single'  # Opsi: 'single' atau 'multilayer'